language: python
python:
  - 2.6
  - 2.7
install:
  - ./.travis_setup
env:
  - DJANGO_VERSION=1.2.7 DJANGO_SETTINGS_MODULE="test_settings_django_12"
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
script: python setup.py test
matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.4